<link rel="stylesheet" type="text/css" href="Skin/bootstrap-5.2.3\css\bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E-COM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=product&a=grid">PRODUCT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=category&a=grid">CATEGORY</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=customer&a=grid">CUSTOMER</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=vendor&a=grid">VENDOR</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=salesman&a=grid">SALESMAN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=shipping&a=grid">SHIPPING METHOD</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=payment&a=grid">PAYMENT METHOD</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=eav_attribute&a=grid">ATTRIBUTE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="index.php?c=admin&a=grid">ADMIN</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
