<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="skin/css/style.css">
	<link rel="stylesheet" type="text/css" href="../skin/css/style.css">

	<style type="text/css">
	table{
	border: 1px solid black;
	width: 100%;
	}

	th,td{
		border: 1px solid black;
		padding: 10px;
		height: 100px;
	}

	</style>

	<title>
		hello
	</title>
</head>
<body>
	<table widht = 100%>
	<tr height = 100px;>
		<td colspan="3" class="border border-info">
			<?php $this->getChild('header')->render();  ?>
		</td>
	</tr>
	<tr height = 40px,>
		<td colspan="3" class="border border-info">
			<?php $this->getChild('message')->render();  ?>
		</td>
	</tr>
	<tr >
		<td width = 20%, class="border border-info">
			<?php $this->getChild('leftsidebar')->render();  ?>
		</td>
		<td width = 70%, class="border border-info">
			<?php $this->getChild('content')->render();  ?>
		</td >
	</tr>
	<tr>
		<td colspan="3">
			<?php $this->getChild('footer')->render();  ?>
		</td>
	</tr>
	</table>
</body>
</html>