<?php
$url = new Model_Core_Url();
$categorys = $this->getCollection()->getData();
?>
<body>
	<div class="dis-1">
		<div class="dis-1a"> MANAGE CATEGORY</div>
		<div class="dis-1a"> <button> <a href=<?php echo $url->getUrl('category','add');?>> ADD CATEGORY</a> </button> </div>
	</div>
	<table>
		<tr>
		<th>CATEGORY ID</th>
		<th>PARENT ID</th>
		<th>PATH</th>
		<th>NAME</th>
		<th>STATUS</th>
		<th>DESCRIPTION</th>
		<th>EDIT</th>
		<th>DELETE</th>
		</tr>
		<?php
			
			foreach ($categorys as $category):
			
		?>
		<tr>
		<td><?php echo $category-> category_id; ?></td>
		<td><?php echo $category-> parent_id; ?></td>
		<td><?php echo $category-> getPathName(); ?></td>
		<td><?php echo $category-> name; ?></td>
		<td><?php echo $category-> getStatusText(); ?></td>
		<td><?php echo $category-> description; ?></td>
		<td> <a href=<?php echo $url->getUrl('category','edit',['id' => $category-> category_id]);?>>EDIT</a> </td>
		<td> <a href=<?php echo $url->getUrl('category','delete',['id' => $category-> category_id]);?>>DELETE</a> </td>
		</tr>
	<?php endforeach ?>
	</table>